### ISSUE TITLE
Does this software give the list or the corresponding points?

### ISSUE THREAD

**Issue by rielt12** [pglira/simpleICP#3] opened 2021-06-16 10:22 UTC
Hi,

Is there anyway to extract which points correspond to eachother using this software?

**Comment by pglira** [comment] 2021-06-16 16:54
In which language you need the corresponding points?

**Comment by rielt12** [comment] 2021-06-17 05:47
Would it be possible to get it in both matlab and python?

**Comment by pglira** [comment] 2021-12-22 08:58
Duplicate of #7

**Closed by pglira** 2021-12-22 08:58 UTC
