### ISSUE TITLE
Displaying the corresponding point clouds in open3D after each iteration

### ISSUE THREAD

**Issue by rllyryan** [pglira/simpleICP#5] opened 2021-08-18 14:06 UTC
Dear pglira,

Your work is amazingly concise and neat!

Could I also find out how do you display the point clouds after each iteration? (Do you use open3d to visualise the point clouds?)

Thank you for you time!

Regards,
rllyryan

**Comment by pglira** [comment] 2021-08-19 07:32
The easiest way is to write an xyz file after each iteration and visualize them afterwards with open3d.

**Comment by pglira** [comment] 2021-12-22 08:58
Duplicate of #7

**Closed by pglira** 2021-12-22 08:58 UTC
